In [14]:
import numpy as np
import random

In [15]:
#Створіть одновимірний масив (вектор) з найменшими непарними числами, не менше 15, та виведіть його значення.
n = 15
a = np.zeros((n), dtype=int)
for i in range(n):
    a[i] = random.randint(1, 100) * 2 + 1
print(a)


[161 131  39 135  49 117 151  95 177 117  69  71 141 153 147]


In [16]:
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями випадкових дійсних чисел від 0 до одиниці
matrix = np.random.rand(3,3)
print(matrix)


[[0.28182871 0.65677488 0.16651593]
 [0.06639511 0.52306987 0.87685656]
 [0.32183405 0.23486798 0.50989723]]


In [17]:
#Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від 0 до 1 та знайдіть мін. елемент.
matrix = np.random.rand(3,3)
print(matrix)
print(matrix.min())

[[0.00288145 0.80135932 0.35978535]
 [0.33120486 0.673265   0.80144898]
 [0.51364125 0.75554944 0.73109213]]
0.0028814477160725716


In [18]:
#Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить мінімальні елементи в кожному рядку.
matrix = np.random.rand(3,3)
print(matrix)
print(matrix.min(axis=1))

[[0.10123856 0.11740226 0.77460401]
 [0.94431304 0.8933228  0.24293743]
 [0.68667543 0.54885318 0.99797756]]
[0.10123856 0.24293743 0.54885318]


In [19]:
#Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами від -5 до 5 та виконайте на них поелементні операції додавання, віднімання та множення
a = np.random.randint(-5, 5, 4)
b = np.random.randint(-5, 5, 4)
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)

[-1  4  4  4]
[ 3 -2 -4 -2]
[2 2 0 2]
[-4  6  8  6]
[ -3  -8 -16  -8]


In [20]:
#Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 10 та знайдіть їх добуток.
a = np.random.randint(1, 10, (3,3))
b = np.random.randint(1, 10, (3,3))
print(a)
print(b)
print(np.dot(a, b))

[[4 9 4]
 [9 5 2]
 [3 1 2]]
[[5 3 9]
 [6 6 3]
 [6 7 9]]
[[ 98  94  99]
 [ 87  71 114]
 [ 33  29  48]]


In [21]:
#Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою.
a = np.random.randint(1, 4, (2,3))
b = np.random.randint(1, 4, (3,3))
print(a)
print(b)
print(np.dot(a, b))


[[1 1 2]
 [3 2 3]]
[[1 2 2]
 [1 2 3]
 [2 2 2]]
[[ 6  8  9]
 [11 16 18]]


In [22]:
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.
a = np.random.randint(1, 12, (3,3))
print(a)
print(np.linalg.inv(a))


[[ 1  7  7]
 [ 8 10  5]
 [ 8  7  6]]
[[-0.12562814 -0.03517588  0.1758794 ]
 [ 0.04020101  0.25125628 -0.25628141]
 [ 0.12060302 -0.24623116  0.23115578]]


In [23]:
#Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -7 до 7 та транспонуйте її.
a = np.random.uniform(-7, 7, (4,4))
print(a)
print(a.T)

[[ 0.84980298 -2.78055889  5.84713048 -6.96214188]
 [ 4.24623525 -6.99858076 -3.88092939 -4.97525802]
 [ 6.26442905 -6.21835616  4.97757627  0.85107113]
 [ 6.6246506   1.59139709 -5.4222246  -0.60764177]]
[[ 0.84980298  4.24623525  6.26442905  6.6246506 ]
 [-2.78055889 -6.99858076 -6.21835616  1.59139709]
 [ 5.84713048 -3.88092939  4.97757627 -5.4222246 ]
 [-6.96214188 -4.97525802  0.85107113 -0.60764177]]


In [24]:
#Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
a = np.random.rand(3,4)
b = np.random.rand(4)
print(a)
print(b)

[[0.82823144 0.62012113 0.32866359 0.04728461]
 [0.88293029 0.7503427  0.74695922 0.15912916]
 [0.63567972 0.59492951 0.76805099 0.06050825]]
[0.73779258 0.02456234 0.96946114 0.15765412]


In [25]:
#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
a = np.random.rand(2,3)
b = np.random.randint(1, 10, 3)
print(a)
print(b)
print(np.dot(a, b))

[[0.48378396 0.8983421  0.15538778]
 [0.50782722 0.26062862 0.31222767]]
[6 3 6]
[6.53005675 5.70221518]


In [13]:
#Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення елементів другого стовпця другої матриці до відповідних елементів першої матриці (поелементне ділення).
a = np.random.randint(1, 10, (9,9))
b = np.random.randint(1, 10, (9,9))
print(a)
print(b)
print(b[:,1] / a[:,1])


[[5 8 5 3 7 1 9 9 9]
 [3 3 8 3 7 1 8 3 9]
 [1 4 8 1 4 8 6 8 6]
 [5 6 8 2 2 2 8 3 1]
 [3 3 5 4 5 7 3 4 8]
 [9 9 6 7 5 5 8 5 6]
 [5 8 4 3 9 4 4 2 5]
 [5 6 6 6 5 5 8 7 6]
 [5 3 2 9 7 2 8 2 6]]
[[9 1 6 4 5 8 8 5 7]
 [9 4 3 5 6 1 6 9 7]
 [6 1 7 9 4 4 3 7 2]
 [1 3 7 5 7 2 3 1 3]
 [2 9 5 8 7 4 3 6 5]
 [4 5 8 1 9 1 3 1 8]
 [7 5 2 6 6 2 8 9 2]
 [3 6 2 8 7 4 6 4 7]
 [4 2 8 3 1 8 9 3 8]]
[0.125      1.33333333 0.25       0.5        3.         0.55555556
 0.625      1.         0.66666667]


In [26]:
#Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток їх елементів.
a = np.random.randint(1, 10, (3,3))
b = np.random.randint(1, 10, (3,3))
print(a)
print(b)
print(a * b)

[[8 1 4]
 [7 2 4]
 [4 7 2]]
[[1 5 7]
 [6 4 4]
 [9 3 5]]
[[ 8  5 28]
 [42  8 16]
 [36 21 10]]


In [27]:
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 5та знайдіть середнє геометричне значення елементів матриці.
a = np.random.randint(1, 5, (3,3))
print(a)
print(np.prod(a) ** (1/9))

[[4 2 2]
 [2 4 2]
 [3 4 4]]
2.846995628505825


In [28]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить найменше за модулем ціле значення в кожному рядку матриці.
a = np.random.uniform(-2, 2, (3,3))
print(a)
print(a.min(axis=1))


[[-1.68867445  1.31133711  1.5470381 ]
 [ 1.69783715 -1.22678054 -1.45116705]
 [-0.34262436 -1.09167006 -1.40850685]]
[-1.68867445 -1.45116705 -1.40850685]


# Висновок:
# У ході виконання лабораторної роботи я ознайомився з основними елементами лінійної алгебри, що є фундаментом для розуміння методів машинного навчання. 
# Виконані завдання дозволили закріпити знання з операцій над векторами та матрицями, включаючи додавання, множення, транспонування та обчислення визначника. 
# Це створює базу для подальшого освоєння складніших алгоритмів і методів у машинному навчанні. Досвід роботи з середовищем Jupyter Notebook (або Colab) також сприяє покращенню практичних навичок кодування.




